### PR TITLE
[CMake] Generate cmake target that other libraries can use

### PR DESCRIPTION
**Pull request by Mike-Devel**
... to express their dependency on this library and retrieve any
configuration information such as the include directory, binary
to link to (if any), transitive dependencies, necessary compiler
options or the required c++ standards level.

### CODE REVIEW

**Comment by Mike-Devel** [comment]
Any comments on this?
I don't claim to understand, why travis is failing for some jobs, but it definetively isn't due to this cmake file.

**Comment by jzmaddock** [comment]
>I don't claim to understand, why travis is failing for some jobs, but it definetively isn't due to this cmake file.

No it's a known clang-3.x issue that we have a workaround for in Boost.Config, but for some reason it's stopped working :(

**Comment by Mike-Devel** [comment]
Rebased PR onto develop and added my alias in the copy right notice

**Comment by Mike-Devel** [comment]
Thanks

**Comment by Lastique** [comment]
Could it be merged to master, please?

**Comment by jzmaddock** [comment]
Done, thanks for the reminder.

**Pull request merged**
